name: "Nix CI"

on:
    push:
    pull_request: 
    workflow_dispatch: 
    schedule:
        - cron: "0 5 * * *"   # daily at 05:00 UTC

jobs: 
    ci:
        uses: KestrelsDevelopment/Workflows/.github/workflows/nix-ci.yml@main
        permissions:
            contents: read
        with:
            check_updated: true
